#include "obj_exporter.h"
#include "../buffer_capture/mesh_extractor.h"
#include <fstream>
#include <sstream>

bool OBJExporter::Export(const CapturedMesh& mesh, const std::string& filepath) {
    std::ofstream obj_file(filepath);
    if (!obj_file.is_open()) {
        return false;
    }
    
    obj_file << "# Generated by Graphics Capture\n";
    obj_file << "# Mesh: " << mesh.name << "\n\n";
    
    // Write vertices
    for (const auto& vertex : mesh.vertices) {
        obj_file << "v " << vertex.position.x << " " << vertex.position.y << " " << vertex.position.z << "\n";
    }
    
    // Write normals
    for (const auto& vertex : mesh.vertices) {
        obj_file << "vn " << vertex.normal.x << " " << vertex.normal.y << " " << vertex.normal.z << "\n";
    }
    
    // Write UVs
    for (const auto& vertex : mesh.vertices) {
        obj_file << "vt " << vertex.uv.x << " " << vertex.uv.y << "\n";
    }
    
    // Write faces
    for (size_t i = 0; i < mesh.indices.size(); i += 3) {
        if (i + 2 >= mesh.indices.size()) break;
        
        uint32_t i0 = mesh.indices[i] + 1; // OBJ indices are 1-based
        uint32_t i1 = mesh.indices[i + 1] + 1;
        uint32_t i2 = mesh.indices[i + 2] + 1;
        
        obj_file << "f " 
                 << i0 << "/" << i0 << "/" << i0 << " "
                 << i1 << "/" << i1 << "/" << i1 << " "
                 << i2 << "/" << i2 << "/" << i2 << "\n";
    }
    
    obj_file.close();
    return true;
}

bool OBJExporter::ExportMultiple(const std::vector<CapturedMesh>& meshes, const std::string& output_dir) {
    // TODO: Export multiple meshes with material library
    return true;
}
