#include "stl_exporter.h"
#include "../buffer_capture/mesh_extractor.h"
#include <fstream>
#include <glm/glm.hpp>

bool STLExporter::ExportASCII(const CapturedMesh& mesh, const std::string& filepath) {
    std::ofstream stl_file(filepath);
    if (!stl_file.is_open()) {
        return false;
    }
    
    stl_file << "solid " << mesh.name << "\n";
    
    // Write faces
    for (size_t i = 0; i < mesh.indices.size(); i += 3) {
        if (i + 2 >= mesh.indices.size()) break;
        
        uint32_t i0 = mesh.indices[i];
        uint32_t i1 = mesh.indices[i + 1];
        uint32_t i2 = mesh.indices[i + 2];
        
        if (i0 >= mesh.vertices.size() || i1 >= mesh.vertices.size() || i2 >= mesh.vertices.size()) {
            continue;
        }
        
        const auto& v0 = mesh.vertices[i0];
        const auto& v1 = mesh.vertices[i1];
        const auto& v2 = mesh.vertices[i2];
        
        // Calculate face normal
        glm::vec3 edge1 = v1.position - v0.position;
        glm::vec3 edge2 = v2.position - v0.position;
        glm::vec3 normal = glm::normalize(glm::cross(edge1, edge2));
        
        stl_file << "  facet normal " << normal.x << " " << normal.y << " " << normal.z << "\n";
        stl_file << "    outer loop\n";
        stl_file << "      vertex " << v0.position.x << " " << v0.position.y << " " << v0.position.z << "\n";
        stl_file << "      vertex " << v1.position.x << " " << v1.position.y << " " << v1.position.z << "\n";
        stl_file << "      vertex " << v2.position.x << " " << v2.position.y << " " << v2.position.z << "\n";
        stl_file << "    endloop\n";
        stl_file << "  endfacet\n";
    }
    
    stl_file << "endsolid " << mesh.name << "\n";
    stl_file.close();
    return true;
}

bool STLExporter::ExportBinary(const CapturedMesh& mesh, const std::string& filepath) {
    std::ofstream stl_file(filepath, std::ios::binary);
    if (!stl_file.is_open()) {
        return false;
    }
    
    // Header (80 bytes)
    char header[80] = {0};
    std::string header_str = "Binary STL generated by Graphics Capture - " + mesh.name;
    header_str.copy(header, std::min(header_str.size(), size_t(80)));
    stl_file.write(header, 80);
    
    // Triangle count
    uint32_t triangle_count = static_cast<uint32_t>(mesh.indices.size() / 3);
    stl_file.write(reinterpret_cast<const char*>(&triangle_count), sizeof(uint32_t));
    
    // Write triangles
    for (size_t i = 0; i < mesh.indices.size(); i += 3) {
        if (i + 2 >= mesh.indices.size()) break;
        
        uint32_t i0 = mesh.indices[i];
        uint32_t i1 = mesh.indices[i + 1];
        uint32_t i2 = mesh.indices[i + 2];
        
        if (i0 >= mesh.vertices.size() || i1 >= mesh.vertices.size() || i2 >= mesh.vertices.size()) {
            continue;
        }
        
        const auto& v0 = mesh.vertices[i0];
        const auto& v1 = mesh.vertices[i1];
        const auto& v2 = mesh.vertices[i2];
        
        // Calculate normal
        glm::vec3 edge1 = v1.position - v0.position;
        glm::vec3 edge2 = v2.position - v0.position;
        glm::vec3 normal = glm::normalize(glm::cross(edge1, edge2));
        
        // Write normal
        stl_file.write(reinterpret_cast<const char*>(&normal.x), sizeof(float));
        stl_file.write(reinterpret_cast<const char*>(&normal.y), sizeof(float));
        stl_file.write(reinterpret_cast<const char*>(&normal.z), sizeof(float));
        
        // Write vertices
        stl_file.write(reinterpret_cast<const char*>(&v0.position.x), sizeof(float));
        stl_file.write(reinterpret_cast<const char*>(&v0.position.y), sizeof(float));
        stl_file.write(reinterpret_cast<const char*>(&v0.position.z), sizeof(float));
        
        stl_file.write(reinterpret_cast<const char*>(&v1.position.x), sizeof(float));
        stl_file.write(reinterpret_cast<const char*>(&v1.position.y), sizeof(float));
        stl_file.write(reinterpret_cast<const char*>(&v1.position.z), sizeof(float));
        
        stl_file.write(reinterpret_cast<const char*>(&v2.position.x), sizeof(float));
        stl_file.write(reinterpret_cast<const char*>(&v2.position.y), sizeof(float));
        stl_file.write(reinterpret_cast<const char*>(&v2.position.z), sizeof(float));
        
        // Attribute byte count
        uint16_t attribute_count = 0;
        stl_file.write(reinterpret_cast<const char*>(&attribute_count), sizeof(uint16_t));
    }
    
    stl_file.close();
    return true;
}
